import React from 'react';
import { css } from '../../app/lib/css.js';
import Avatar from '../../components/atoms/Avatar.jsx';
import Badge from '../../components/atoms/Badge.jsx';
import Button from '../../components/atoms/Button.jsx';
import Card from '../../components/atoms/Card.jsx';
import SectionHeader from '../../docs/SectionHeader.jsx';

export default function CardsSection({ v }) {
  return (
<section className="section" id="cards" data-screen-label="Cards">
<SectionHeader kicker={"02 — المكوّنات"} title={"البطاقات"} desc={"أسطح مرتفعة ومستديرة ترتفع عند المرور — حاوية النظام الأساسية."} />
<p className="subhead">بطاقة منتج</p>
<div className="grid cols3">
<Card variant="pcard"><div className="ph"><span className="ph-tag">عمل فني</span></div><div className="pcard-body"><div className="fx ac jb" style={css('display: flex')}><span className="pcard-title" style={css('padding-left: 8px')}>Pixel M7 #204</span><Badge variant="green"><span className="dot"></span>موثّق</Badge></div><p className="pcard-text">مقتنى رقمي توليدي على السلسلة من مجموعة M7asmari التأسيسية.</p><div className="pcard-foot"><span className="price numjoin">1.24 ETH</span><Button variant="brand sm">اقتناء</Button></div></div></Card>
<Card variant="pcard"><div className="ph" style={css('background-color:var(--brand-soft)')}><span className="ph-tag">معاينة المحفظة</span></div><div className="pcard-body"><div className="fx ac jb" style={css('display: flex')}><span className="pcard-title" style={css('padding-left: 8px')}>المحفظة الرئيسية</span><Badge variant="neutral">افتراضية</Badge></div><p className="pcard-text">تابِع الأرصدة والنشاط الأخير بنظرة واحدة، في مكان واحد.</p><div className="pcard-foot"><span className="price mono numjoin">$4,820.55</span><Button variant="secondary sm">فتح</Button></div></div></Card>
<Card variant="pcard"><div className="ph" style={css('background-color:var(--success-soft)')}><span className="ph-tag">تجمّع التخزين</span></div><div className="pcard-body" style={css('display: block')}><div className="fx ac jb" style={css('display: flex')}><span className="pcard-title" style={css('padding-left: 8px')}>التخزين</span><Badge variant="gold"><span className="dot"></span><span className="numjoin">4.1% APY</span></Badge></div><p className="pcard-text">اكسب مكافآت بتأمين الشبكة عبر حماية لا تتوقّف.</p><div><br /></div><p></p><div className="pcard-foot"><span className="price">يكسب</span><Button variant="ghost sm">إدارة</Button></div></div></Card>
</div>
<p className="subhead" style={css('margin-top:34px')}>بطاقة مزية — صورة 16:9 + رابط متحرّك</p>
<div className="grid cols2">
<Card variant="fcard"><div className="fcard-img"><span className="ph-tag">صورة 16:9</span></div><div className="fcard-body"><div className="fcard-title">تصميم عصري</div><p className="fcard-text">واجهة نظيفة وبديهية مبنية على أحدث مبادئ التصميم، مهيّأة لأفضل تجربة استخدام.</p><span className="arrowlink">اعرف المزيد<svg viewBox="0 0 24 24"><path d="M19 12H5M12 19l-7-7 7-7"></path></svg></span></div></Card>
<Card variant="fcard"><div className="fcard-img" style={css('background-color:var(--brand-soft)')}><span className="ph-tag">صورة 16:9</span></div><div className="fcard-body"><div className="fcard-title">تحليلات متقدّمة</div><p className="fcard-text">أدوات تحليل قوية تساعدك على فهم مستخدميك واتخاذ قرارات مبنية على البيانات.</p><span className="arrowlink">احجز عرضًا<svg viewBox="0 0 24 24"><path d="M19 12H5M12 19l-7-7 7-7"></path></svg></span></div></Card>
</div>
<p className="subhead" style={css('margin-top:34px')}>بطاقة سير عمل — تكشف الوصف والوسوم عند المرور</p>
<div className="grid cols3">
<Card variant="wcard"><div className="wcard-img"><div className="ph"></div></div><div className="wcard-body"><div className="wcard-top"><div><div className="wcard-meta"><span>حُدّث قبل ساعتين</span><span>•</span><span className="wstat on"></span><span>نشِط</span></div><div className="wcard-title">سير عمل الإطلاق</div></div><button className="wmore" aria-label="خيارات"><svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle></svg></button></div><div className="wreveal"><div className="wreveal-in"><p className="wcard-desc">أتمتة كاملة لخطوات الإصدار: من تجهيز المحتوى حتى النشر والمراجعة النهائية.</p><div className="wtags"><Badge variant="neutral">أتمتة</Badge><Badge variant="neutral">إصدار</Badge><Badge variant="neutral">مراجعة</Badge></div></div></div></div><div className="wcard-foot"><div className="avgroup"><Avatar variant="sm"><img src="assets/avatar.jpg" alt="" /></Avatar><Avatar variant="sm" style={css('background:#16bd74;color:#042c1c')}>ب</Avatar><Avatar variant="sm" style={css('background:#f5a623;color:#3f2305')}>م</Avatar></div><div className="wact"><span className="wactbtn" data-action="تم" data-tone="success" style={css('background:var(--success)')}><svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"></path></svg></span><span className="wactbtn" data-action="تثبيت" data-tone="info" style={css('background:var(--brand)')}><svg viewBox="0 0 24 24"><path d="M12 17v5M9 3h6l-1 7 3 2H7l3-2-1-7z"></path></svg></span></div></div></Card>
<Card variant="wcard"><div className="wcard-img"><div className="ph" style={css('background-color:var(--success-soft)')}></div></div><div className="wcard-body"><div className="wcard-top"><div><div className="wcard-meta"><span>حُدّث أمس</span><span>•</span><span className="wstat off"></span><span>متوقّف</span></div><div className="wcard-title">مزامنة البيانات</div></div><button className="wmore" aria-label="خيارات"><svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle></svg></button></div><div className="wreveal"><div className="wreveal-in"><p className="wcard-desc">تزامن دوري للأصول بين المحافظ مع سجلّ كامل لكل عملية وإمكانية التراجع.</p><div className="wtags"><Badge variant="neutral">مزامنة</Badge><Badge variant="neutral">جدولة</Badge></div></div></div></div><div className="wcard-foot"><div className="avgroup"><Avatar variant="sm" style={css('background:#627eea')}>س</Avatar><Avatar variant="sm" style={css('background:#fb3d18')}>د</Avatar></div><div className="wact"><span className="wactbtn" data-action="تذكير" data-tone="info" style={css('background:var(--warning)')}><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="M12 8v4l3 2"></path></svg></span></div></div></Card>
<Card variant="wcard"><div className="wcard-img"><div className="ph" style={css('background-color:var(--warning-soft)')}></div></div><div className="wcard-body"><div className="wcard-top"><div><div className="wcard-meta"><span>حُدّث الآن</span><span>•</span><span className="wstat on"></span><span>نشِط</span></div><div className="wcard-title">تنبيهات الأمان</div></div><button className="wmore" aria-label="خيارات"><svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle></svg></button></div><div className="wreveal"><div className="wreveal-in"><p className="wcard-desc">مراقبة لحظية للمعاملات المشبوهة مع إشعارات فورية وإجراءات حماية تلقائية.</p><div className="wtags"><Badge variant="neutral">أمان</Badge><Badge variant="neutral">مراقبة</Badge><Badge variant="neutral">تنبيه</Badge></div></div></div></div><div className="wcard-foot"><div className="avgroup"><Avatar variant="sm" style={css('background:#16bd74;color:#042c1c')}>ن</Avatar><Avatar variant="sm"><img src="assets/avatar.jpg" alt="" /></Avatar></div><div className="wact"><span className="wactbtn" data-action="تنبيه" data-tone="error" style={css('background:var(--danger)')}><svg viewBox="0 0 24 24"><path d="M12 3 2 20h20L12 3zM12 10v4M12 17v.5"></path></svg></span><span className="wactbtn" data-action="تثبيت" data-tone="info" style={css('background:var(--brand)')}><svg viewBox="0 0 24 24"><path d="M12 17v5M9 3h6l-1 7 3 2H7l3-2-1-7z"></path></svg></span></div></div></Card>
</div>
</section>
  );
}
